/** Curated destinations for search-as-you-type; users can still type any custom place. */
export const DESTINATION_SUGGESTIONS: string[] = [
  "Agra, India",
  "Amsterdam, Netherlands",
  "Andaman & Nicobar, India",
  "Athens, Greece",
  "Auckland, New Zealand",
  "Bali, Indonesia",
  "Bangalore, India",
  "Bangkok, Thailand",
  "Barcelona, Spain",
  "Beijing, China",
  "Bengaluru, India",
  "Berlin, Germany",
  "Budapest, Hungary",
  "Buenos Aires, Argentina",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "Chennai, India",
  "Chiang Mai, Thailand",
  "Chicago, USA",
  "Colombo, Sri Lanka",
  "Copenhagen, Denmark",
  "Delhi, India",
  "Dubai, UAE",
  "Dublin, Ireland",
  "Edinburgh, UK",
  "Florence, Italy",
  "Goa, India",
  "Hanoi, Vietnam",
  "Helsinki, Finland",
  "Ho Chi Minh City, Vietnam",
  "Hong Kong",
  "Hyderabad, India",
  "Istanbul, Turkey",
  "Jaipur, India",
  "Jodhpur, India",
  "Kathmandu, Nepal",
  "Kerala, India",
  "Kochi, India",
  "Kolkata, India",
  "Krakow, Poland",
  "Kuala Lumpur, Malaysia",
  "Kyoto, Japan",
  "Lisbon, Portugal",
  "London, UK",
  "Los Angeles, USA",
  "Madrid, Spain",
  "Maldives",
  "Manali, India",
  "Marrakech, Morocco",
  "Melbourne, Australia",
  "Mexico City, Mexico",
  "Mumbai, India",
  "Mussoorie, India",
  "New York, USA",
  "Paris, France",
  "Petra, Jordan",
  "Phuket, Thailand",
  "Porto, Portugal",
  "Prague, Czech Republic",
  "Puducherry, India",
  "Reykjavik, Iceland",
  "Rishikesh, India",
  "Rome, Italy",
  "San Francisco, USA",
  "Seoul, South Korea",
  "Shimla, India",
  "Singapore",
  "Stockholm, Sweden",
  "Sydney, Australia",
  "Taipei, Taiwan",
  "Tokyo, Japan",
  "Udaipur, India",
  "Varanasi, India",
  "Venice, Italy",
  "Vienna, Austria",
  "Zurich, Switzerland",
].sort((a, b) => a.localeCompare(b));
